# Generated by Django 6.0.3 on 2026-03-23 14:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_content_description_blocks_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontent',
            name='body',
            field=models.TextField(blank=True, help_text='Main body content. Can be used together with blocks.'),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='description',
            field=models.TextField(blank=True, help_text='Long-form summary to describe this content item.'),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Short teaser text for cards and list previews.', max_length=500),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='industry',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('product', 'Product')], help_text='Industry type that controls which detail model should be attached.', max_length=32),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible JSON object for extra machine-readable fields.'),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Optional owner reference. Can be left empty for single-admin workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='When content becomes visible. Required for published status.', null=True),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Optional SEO description for meta tags.', max_length=500),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. Falls back to title when empty.', max_length=255),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='slug',
            field=models.SlugField(help_text='URL-safe unique identifier, e.g. modern-family-home.', unique=True),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing state of this content.', max_length=16),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='title',
            field=models.CharField(help_text='Public title shown on listings and detail pages.', max_length=255),
        ),
        migrations.AlterField(
            model_name='basecontent',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, help_text='Optional end date/time. Must be later than publish date/time.', null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('hero', 'Hero'), ('gallery', 'Gallery'), ('cta', 'Call To Action')], help_text='Block renderer type used by the frontend.', max_length=32),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='body',
            field=models.TextField(blank=True, help_text='Optional rich text/body copy for this block.'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.ForeignKey(help_text='Parent content item for this block.', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.basecontent'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Turn block visibility on/off without deleting it.'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for block config, e.g. {"cta_label": "Book now", "cta_href": "/contact"}.'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order within this content item. Must be unique per content.'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, help_text='Optional block heading.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='alt_text',
            field=models.CharField(help_text='Accessibility description of the image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption shown under the image.', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content',
            field=models.ForeignKey(help_text='Parent content item for this image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.basecontent'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(help_text='Upload image file. Stored under media/cms/images/...', upload_to='cms/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark as the main/cover image. Only one primary image is allowed per content.'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order among images for this content.'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='content',
            field=models.OneToOneField(help_text='Linked base content. Industry must be Product.', on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='cms.basecontent'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Product price.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='sku',
            field=models.CharField(help_text='Unique stock-keeping unit identifier.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity available.'),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='address_line',
            field=models.CharField(help_text='Property street address line.', max_length=255),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='area_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Optional interior area in square feet.', null=True),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Number of bathrooms. Supports halves, e.g. 2.5.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of bedrooms.'),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='content',
            field=models.OneToOneField(help_text='Linked base content. Industry must be Real Estate.', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_details', to='cms.basecontent'),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO currency code, e.g. USD.', max_length=3),
        ),
        migrations.AlterField(
            model_name='realestatedetails',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, help_text='Listing price for the property.', max_digits=12),
        ),
    ]
