# Generated by Django 6.0.3 on 2026-03-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_basecontent_body_alter_basecontent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='cta_href',
            field=models.CharField(blank=True, help_text='CTA destination URL/path, e.g. /contact.', max_length=500),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='cta_label',
            field=models.CharField(blank=True, help_text='CTA button label. Recommended for CTA block type.', max_length=120),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='cta_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')], default='primary', help_text='CTA visual style used by frontend.', max_length=20),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='cta_target',
            field=models.CharField(choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', help_text='Open link in same tab or new tab.', max_length=10),
        ),
        migrations.CreateModel(
            name='ContentMetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Metadata key, e.g. city, category, listing_type.', max_length=100)),
                ('value', models.CharField(help_text='Metadata value as plain text.', max_length=255)),
                ('content', models.ForeignKey(help_text='Parent content item for this metadata entry.', on_delete=django.db.models.deletion.CASCADE, related_name='meta_items', to='cms.basecontent')),
            ],
            options={
                'ordering': ['content_id', 'key'],
                'constraints': [models.UniqueConstraint(fields=('content', 'key'), name='cms_contentmetaitem_unique_key_per_content')],
            },
        ),
    ]
